package it.polimi.ingsw.server.controller;

public enum UserAction {
    GET_FROM_MARKET, BUY_DEVCARD, START_PRODUCTION,
    DISCARD_LEADCARD, PLAY_LEADCARD, MOVE_RESOURCES,
    SETUP_DRAW, SELECT_LEADCARD, INITIAL_DISPOSITION,
    RESOURCE_SELECTION, LORENZO_ACTION
}
